### ISSUE TITLE
Confusion about the candidate layer in stable-diffusion-xl

### ISSUE THREAD

**Issue by Xyporz** [Darkbblue/generic-diffusion-feature#1]
Very nice work and codebase!

However, I have a little confusion. I found by show_all_layers that stable-diffusion-xl has a total of 522 layers of intermediate output, while config_xl_full.json lists 279 layers of output, but I found that there are non-overlapping parts between them. 

For example, all increments and ffn-inners (such as down-level1-repeat0-res-increment and down-level1-repeat0-vit-block0-ffn-inner) in config_xl_full.json are not in the list of show_all_layers, thus only 216 features are actually preserved by extract_feature.py using config_xl_full.json.

**Comment by Darkbblue** [comment]
> Very nice work and codebase!
> 
> However, I have a little confusion. I found by show_all_layers that stable-diffusion-xl has a total of 522 layers of intermediate output, while config_xl_full.json lists 279 layers of output, but I found that there are non-overlapping parts between them.
> 
> For example, all increments and ffn-inners (such as down-level1-repeat0-res-increment and down-level1-repeat0-vit-block0-ffn-inner) in config_xl_full.json are not in the list of show_all_layers, thus only 216 features are actually preserved by extract_feature.py using config_xl_full.json.

Thanks for your feedback! It turns out that I've missed some feature extraction spots while migrating from an older diffusers version to the current one (these spots are not used in our final feature choices, so I didn't notice this issue). I've fixed this issue with the new commit.
Additionally, now show_all_layers will also generate a config file, based on which I've updated the two config_full.json files.
Please let me know if there's still some problem!
